### PR TITLE
video: mxc epdc: Add QOS handling in driver

### PR DESCRIPTION
**Pull request by larsim**
Enables QOS support in EPDC hardware

### CODE REVIEW

**Review by steinarbakkemo — APPROVED** [review]
No further comments

**Comment by patrickhisnibrataas** [comment]
@larsim Should we test a release from this branch before merging to master?

**Comment by larsim** [comment]
@patrickhisnibrataas That would be nice.

**Comment by schultzern** [comment]
@larsim green light to merge this bad boy?

**Pull request merged**
